#!/bin/sh

# Change the theme
sed -i 's%^ZSH_THEME=.*$%ZSH_THEME="pv"%' ~/.zshrc

# Change the custom directory
sed -i 's%# ZSH_CUSTOM=.*%ZSH_CUSTOM=~/.ohmyzsh-custom%' ~/.zshrc

# Change the loaded plugins
sed -i 's%^plugins=.*%plugins=(git poetry)%' ~/.zshrc

# check if the /workspaces/.codespaces/.persistedshare/dotfiles directory exists and then echo "foo"
if [ -d "/workspaces/.codespaces/.persistedshare/dotfiles" ]; then
  ln -s /workspaces/.codespaces/.persistedshare/dotfiles/.ohmyzsh-custom ~/.ohmyzsh-custom
fi
